run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis
    - typecheck     # Type-checks Go code
    - unused        # Checks for unused constants, variables, functions and types
    - gofmt         # Checks code formatting
    - goimports     # Checks import formatting
    - misspell      # Finds commonly misspelled words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gosec         # Security issues
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo       # Computes cyclomatic complexity
    - dupl          # Code clone detection
    - goconst       # Finds repeated strings that could be replaced by a constant
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - prealloc      # Finds slice declarations that could potentially be preallocated

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude known false positives
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

    # Allow common patterns in main.go
    - path: cmd/
      linters:
        - gochecknoglobals

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true