// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"
)

// MockPriceOracle is an autogenerated mock type for the PriceOracle type
type MockPriceOracle struct {
	mock.Mock
}

type MockPriceOracle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPriceOracle) EXPECT() *MockPriceOracle_Expecter {
	return &MockPriceOracle_Expecter{mock: &_m.Mock}
}

// FetchPrice provides a mock function with given fields: ctx, tokenAddr
func (_m *MockPriceOracle) FetchPrice(ctx context.Context, tokenAddr common.Address) (float64, bool) {
	ret := _m.Called(ctx, tokenAddr)

	if len(ret) == 0 {
		panic("no return value specified for FetchPrice")
	}

	var r0 float64
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) (float64, bool)); ok {
		return rf(ctx, tokenAddr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) float64); ok {
		r0 = rf(ctx, tokenAddr)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address) bool); ok {
		r1 = rf(ctx, tokenAddr)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockPriceOracle_FetchPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPrice'
type MockPriceOracle_FetchPrice_Call struct {
	*mock.Call
}

// FetchPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenAddr common.Address
func (_e *MockPriceOracle_Expecter) FetchPrice(ctx interface{}, tokenAddr interface{}) *MockPriceOracle_FetchPrice_Call {
	return &MockPriceOracle_FetchPrice_Call{Call: _e.mock.On("FetchPrice", ctx, tokenAddr)}
}

func (_c *MockPriceOracle_FetchPrice_Call) Run(run func(ctx context.Context, tokenAddr common.Address)) *MockPriceOracle_FetchPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *MockPriceOracle_FetchPrice_Call) Return(_a0 float64, _a1 bool) *MockPriceOracle_FetchPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPriceOracle_FetchPrice_Call) RunAndReturn(run func(context.Context, common.Address) (float64, bool)) *MockPriceOracle_FetchPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPriceOracle creates a new instance of MockPriceOracle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPriceOracle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPriceOracle {
	mock := &MockPriceOracle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
